"""second migration

Revision ID: ac12f6d05231
Revises: dc13bf25bdbd
Create Date: 2023-07-24 14:41:08.294999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac12f6d05231'
down_revision = 'dc13bf25bdbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
