"""second

Revision ID: 31dff17d9b0a
Revises: 27a507dd5bcf
Create Date: 2023-07-24 08:07:35.316435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31dff17d9b0a'
down_revision = '27a507dd5bcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
