"""migrations custom

Revision ID: 531e95db785c
Revises: 619507ec3ffa
Create Date: 2023-07-21 14:34:30.752479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531e95db785c'
down_revision = '619507ec3ffa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
