"""add relationship between user and todo

Revision ID: 619507ec3ffa
Revises: 3489a392f57a
Create Date: 2023-07-21 12:16:51.090442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619507ec3ffa'
down_revision = '3489a392f57a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###
